# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='js',
            new_name='script',
        ),
    ]
